definitions:
  main.Video:
    properties:
      age:
        type: integer
      genre:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /videos:
    post:
      consumes:
      - application/json
      description: Create a new video with the specified title, description, and genre
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.Video'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.Video'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create a new video
      tags:
      - videos
swagger: "2.0"
